# Copyright (c) 2026 BeardedSheeep

FROM apache/airflow:2.10.5-python3.12

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /opt/airflow/project

COPY --chown=airflow:0 pyproject.toml uv.lock README.md LICENSE ./
COPY --chown=airflow:0 realtimedatastreaming ./realtimedatastreaming

RUN pip install --no-cache-dir .
